### ISSUE TITLE
Refactor `get_issues` to accept `**kwargs` as params and make `since_date` is an optional string.

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/Python-Community-News#56]
Does this also support filtering by issues that are currently open? e.g. we've closed #19 in favor of a couple of other specific issues that replaced it.

_Originally posted by @jonafato in https://github.com/kjaymiller/Python-Community-News/pull/48#discussion_r960221480_

**Comment by jonafato** [comment]
I don't see this as a general `*args`, `**kwargs` thing. My comment was specifically about open issues, because I don't see a reason we'd want to cover issues that are already closed. i.e. this comment is about the behavior of the function to fetch relevant issues for a show, not the function signature.

**Comment by kjaymiller** [comment]
I only mention doing it this way as it keeps things open for future development. Also considering `get_issues` is how we're pulling many issues I can see it being useful to have some flexibility for 

- Pull Topics
- Pull Conferences Covered
- Pull Big Topics

**Comment by kjaymiller** [comment]
The updated solution resolved the issue in a different way
