### ISSUE TITLE
[DISCUSS] How do you test GH Actions

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/Python-Community-News#69]
I can't see a good way to allow others to develop actions and actually test them. Is there a recommended approach?

**Comment by jonafato** [comment]
I don't know of an official GitHub-provided solution for this, but there are a couple of options I've used:

1. Modify the trigger for the action to run on the pull request that's introducing or modifying it. This will let you trigger an action from the PR while developing it, and then you can switch it to be the intended trigger before marking it as ready for review / merge.
2. Use something like https://github.com/nektos/act to run actions locally (which has some caveats regarding actions that need a token in order to work, since GitHub Actions provides a token by default but `act` cannot).

**Comment by kjaymiller** [comment]
I know that the Project actions did require a token but my guess would be that everything within the repo would not require it.

**Comment by jonafato** [comment]
Generally private or rate-limited APIs are going to require this, but I've also used it to e.g. create pull requests with an access token. If you don't run into the issue, nothing to worry about; but there are workarounds even if you do need one that require a bit of setup.
